### ISSUE TITLE
Lack of memes

### ISSUE THREAD

**Issue by abrarsim2017** [noahwoinicki/g5_p2#8]
No website is complete without some boomer humor. We NEED MORE MINION MEMES!!!

pls add some thanks

**Comment by ricardoduenez** [comment]
![Minion-Memes-005c201a48715ee1d5af42df028aae1d](https://user-images.githubusercontent.com/63133331/92655815-93c01f00-f2b7-11ea-9ae2-6e73ff0ab034.jpg)

**Comment by ricardoduenez** [comment]
![wMMxKeChTQvufTO-800x450-noPad](https://user-images.githubusercontent.com/63133331/92655941-cd912580-f2b7-11ea-8967-5a8899804594.jpg)

**Comment by ricardoduenez** [comment]
![images](https://user-images.githubusercontent.com/63133331/92656001-e7cb0380-f2b7-11ea-9ef7-12668e1747aa.jpg)
